replace_items:
  diamond_sword: default_tools:diamond_sword
  diamond_axe: default_tools:diamond_axe
  diamond_pickaxe: default_tools:diamond_pickaxe
  diamond_shovel: default_tools:diamond_shovel
  diamond_hoe: default_tools:diamond_hoe
  diamond_helmet: default_tools:diamond_helmet
  diamond_chestplate: default_tools:diamond_chestplate
  diamond_leggings: default_tools:diamond_leggings
  diamond_boots: default_tools:diamond_boots
  iron_sword: default_tools:iron_sword
  iron_axe: default_tools:iron_axe
  iron_pickaxe: default_tools:iron_pickaxe
  iron_shovel: default_tools:iron_shovel
  iron_hoe: default_tools:iron_hoe
  iron_helmet: default_tools:iron_helmet
  iron_chestplate: default_tools:iron_chestplate
  iron_leggings: default_tools:iron_leggings
  iron_boots: default_tools:iron_boots
  golden_sword: default_tools:golden_sword
  golden_axe: default_tools:golden_axe
  golden_pickaxe: default_tools:golden_pickaxe
  golden_shovel: default_tools:golden_shovel
  golden_hoe: default_tools:golden_hoe
  golden_helmet: default_tools:golden_helmet
  golden_chestplate: default_tools:golden_chestplate
  golden_leggings: default_tools:golden_leggings
  golden_boots: default_tools:golden_boots
  chainmail_hoe: default_tools:chainmail_hoe
  chainmail_helmet: default_tools:chainmail_helmet
  chainmail_chestplate: default_tools:chainmail_chestplate
  chainmail_leggings: default_tools:chainmail_leggings
  chainmail_boots: default_tools:chainmail_boots
  stone_sword: default_tools:stone_sword
  stone_axe: default_tools:stone_axe
  stone_pickaxe: default_tools:stone_pickaxe
  stone_shovel: default_tools:stone_shovel
  stone_hoe: default_tools:stone_hoe
  wooden_sword: default_tools:wooden_sword
  wooden_axe: default_tools:wooden_axe
  wooden_pickaxe: default_tools:wooden_pickaxe
  wooden_shovel: default_tools:wooden_shovel
  wooden_hoe: default_tools:wooden_hoe
  bow: bows:shortbow
  crossbow: bows:pistol_crossbow